# Generated by Django 6.0.6 on 2026-06-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Entrega')),
                ('description', models.TextField(verbose_name='Descrição do que entrega')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='profile_app.profile')),
            ],
            options={
                'verbose_name': 'O Que Eu Entrego',
                'verbose_name_plural': 'O Que Eu Entrego',
                'ordering': ['order'],
            },
        ),
    ]
