# Generated by Django 6.0.6 on 2026-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='icon',
            field=models.CharField(default='fa-truck', help_text='Insira um Emoji ou classe de ícone (ex: 🌐, 📱)', max_length=50, verbose_name='Ícone'),
            preserve_default=False,
        ),
    ]
